
export interface IUser extends Document{
    username:string;
    password:string;
    ClientId:string;
    ClientName:string;
    ProcessDate:string;
    EndDate:string;
    Consulate:string;
    FeePd:string;
    WorkerId:string;
    FirstName:string;
    LastName:string;
    LastName2:string;
    Gender:string;
    Address:string;
    City:string;
    State:string;
    ZipCode:string;
    Phone:string;
    Phone2:string;
    Email:string;
    Passport:string;
    PassportDate:string;
    PPStatus:string;
    New:string;
    CommentMX:string;
    RecrID:string;
    Petition:string;
    H2:string;
    Interview:string;
    DepositMade:string;
    DepositNumber:string;
    Packet:string;
    WorkerStatus:string;
    DOB:string;
    StatusIn:string;
    Renewal:string;
    IllegalPresence:string;
    uniqueId:string;

}